version: "2.1"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    #network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "data_volume:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - application-network

  database:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: archives
      MYSQL_USER: applicationEvent
      MYSQL_PASSWORD: dhcllkrjkdl@#4984834
      MYSQL_ROOT_PASSWORD: x!ekxxlo098@ec
    networks:
      - application-network

networks:
  application-network:
    driver: bridge

volumes:
  data_volume:
    driver: local
