AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MessageSender

  Sample SAM Template for MessageSender

Globals:
  Function:
    Timeout: 3

Resources:
  ReceiveMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: receive_messages/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /receive_message
            Method: get

Outputs:
  ReceiveMessageFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Receive Messages function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/receive_message/"
  ReceiveMessageFunction:
    Description: "Receive Message Lambda Function ARN"
    Value: !GetAtt ReceiveMessageFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Receive Message function"
    Value: !GetAtt ReceiveMessageFunctionRole.Arn
