AWSTemplateFormatVersion: 2010-09-09
Description: Create stack to file-application
Resources:
  S3Files:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: files

  S3Repository:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: repository

  SqsFiles:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: files

  DefaultRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DefaultRole
      Description: Default role from lambdas
      AssumeRolePolicyDocument:
        Version: 2010-10-17
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
