AWSTemplateFormatVersion: 2010-09-09
Description: Terraform to file-application
Resources:
  S3Instance:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: files

  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: files

  DefaultRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DefaultRole
      Description: Default role from lambdas
      AssumeRolePolicyDocument:
        Version: 2010-10-17
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"

  HelloWorldLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: fileb://sample.zip
      FunctionName: SampleLambda
      Handler: index.handler
      Runtime: nodejs12.x
      Role: !GetAtt DefaultRole.Arn
